name: "Delete Git Tag from Repository"
description: "Delete a git tag using GitHub API"
author: Lee Lott

inputs:
  tag-name:
    description: 'Name of the tag to create'
    required: true
  org-name:
    description: 'The name of the GitHub organization'
    required: true
  repo-name:
    description: 'The name of the repository'
    required: true
  token:
    description:  'GitHub token with access to Git tags'
    required: true

outputs:
  result:
    description: 'Result of the attempt to delete the git tag ("success", "not-found" or "failure")'
    value: ${{ steps.action.outputs.result }}
  error-message:
    description: 'Error message if the action fails'
    value: ${{ steps.action.outputs.error-message }}

runs:
  using: "composite"
  steps:
    - name: Delete Tag
      id: action
      shell: pwsh
      run: |
        Import-Module "${{ github.action_path }}/modules/Remove-GitTag.psm1"        
        Remove-GitTag `
          -RepoName "${{ inputs.repo-name }}" `
          -OrgName "${{ inputs.org-name }}" `
          -TagName "${{ inputs.tag-name }}" `
          -Token "${{ inputs.token }}"